Categories
annidrumm/influencer-finder pull request #5
Opened 2020-09-03 14:17 UTC by annidrumm

This pull request is linked to this user story: #2 

- A category page which directs to a list of all influencer profiles  
- A button to go back to the category page
- A headline that changes on each page

2020-09-03 15:27 UTC, jennydely requested changes
Looks quite nice, just some small changes, maybe for a cleaner code.

2020-09-03 15:27 UTC, jennydely commented on src/components/CategoryButton/CategoryButton.js
> +
why is the vase icon imported as Component "InteriorIcon" with big I ?

2020-09-03 15:27 UTC, jennydely commented on src/components/CategoryButton/CategoryButton.js
> +        </ButtonStyled>
I think, we shouldnt use emptystrings in alt text like alt=" fashion mannequin" better using alt="fashion_mannequin"

For me it's a bit strange to have an styled h2 including into the Button, who is both named Button, maybe you can just write <h2> and include the textstyle in the styled component ? with && h2 { } styling. Or just name it into StyledH2. I'm not sure which is the better solution here.

2020-09-03 15:27 UTC, jennydely commented on src/components/Headline/Headline.js
> +  margin: 20px 0;
why do you use a grid-column here? I cant see your grid in the app?

2020-09-03 15:27 UTC, maximiliangustmann reviewed
Good job. Most of the comments were naming and a lot of them I suggest changing CategoryButton to CategoryButtons since your component shows multiple buttons. Forgive me if I'ver overseen some of them.

2020-09-03 15:27 UTC, maximiliangustmann commented on src/App.js
> +      <Route path="/InfluencerList" component={InfluencerList}>
```suggestion
      <Route path="/influencerlist" component={InfluencerList}>
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/App.js
> +        <CategoryPage />
Is this your homepage? The name might be a bit missleading then.

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.js
> +import InteriorIcon from '../../icons/vase.svg'
```suggestion
import interiorIcon from '../../icons/vase.svg'
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.js
> +          <img src={InteriorIcon} alt="interior vase" />
```suggestion
          <img src={interiorIcon} alt="interior vase" />
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.js
> +          <ButtonTextStyled>Food</ButtonTextStyled>
Looks a bit weird to call it IconsStyled but ButtonTextStyled.

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.js
> +export default function CategoryButton() {
```suggestion
export default function CategoryButtons() {
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.stories.js
> +import CategoryButton from './CategoryButton'
```suggestion
import CategoryButtons from './CategoryButtons'
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.stories.js
> +  component: CategoryButton,
```suggestion
  component: CategoryButtons,
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.stories.js
> +  return <CategoryButton />
```suggestion
  return <CategoryButtons />
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.test.js
> +import CategoryButton from './CategoryButton'
```suggestion
import CategoryButtons from './CategoryButtons'
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.test.js
> +describe('CategoryButton', () => {
```suggestion
describe('CategoryButtons', () => {
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.test.js
> +  it('renders CategoryButton correctly', () => {
```suggestion
  it('renders CategoryButtons correctly', () => {
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.test.js
> +    const tree = renderer.create(<CategoryButton />)
```suggestion
    const tree = renderer.create(<CategoryButtons />)
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/pages/CategoryPage/CategoryPage.js
> +import CategoryButton from '../../components/CategoryButton/CategoryButton'
```suggestion
import CategoryButtons from '../../components/CategoryButton/CategoryButtons'
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/pages/CategoryPage/CategoryPage.js
> +      <CategoryButton />
```suggestion
      <CategoryButtons />
```

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.js
> +  }
Do all buttons lead to the same page? If so why do you need so many buttons? Also I would consider to use react router here as well.

2020-09-03 15:27 UTC, maximiliangustmann commented on src/components/CategoryButton/CategoryButton.js
> +    let path = `InfluencerList`
```suggestion
    let path = `influencerlist`
```

2020-09-04 08:07 UTC, annidrumm commented on src/components/CategoryButton/CategoryButton.js
> +
I named it now to what the icons show like vase, plane etc.

2020-09-04 08:08 UTC, annidrumm commented on src/components/CategoryButton/CategoryButton.js
> +        </ButtonStyled>
You are right, it could be a bit misleading. I went with the option H2Styled so that it fits with my other naming

2020-09-04 08:09 UTC, annidrumm commented on src/App.js
> +        <CategoryPage />
This will not gonna be my homepage. There will come more pages in my next stories(:

2020-09-04 08:11 UTC, annidrumm commented on src/components/CategoryButton/CategoryButton.js
> +  }
That is correct for this story. For now all the buttons lead to the main list which includes all categories. In the next story I would like to filter them.

2020-09-04 08:19 UTC, annidrumm commented on src/components/Headline/Headline.js
> +  margin: 20px 0;
I need this for my headline and the go back arrow otherwise the positions are not correct

2020-09-04 09:35 UTC, JonasImm commented
Hey, 
maybe a general thought of mine: You have one pull-request for **category** but seem to be working e.g. on **influencer list**.  It might be easier to follow and would create a cleaner history if you would split your pull-requests. For me, category would suggest the main category page, after that you could create one for influencer list.
🚀

2020-09-04 09:51 UTC, manuelpapa reviewed
Great job! Can't wait for the final app!

2020-09-04 09:51 UTC, manuelpapa commented on public/index.html
> +      href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;600&display=swap"
In a later step you can think of self-hosting the google fonts instead of embedding them. 
[How to self-host google-fonts](https://dev.to/kelli/how-to-self-host-google-fonts-on-your-own-server-d4i)
A reason to do so could be e.g. a better performance on less modern browsers or devices (e.g. Edge).

2020-09-04 09:51 UTC, manuelpapa commented on src/App.js
> +    <Switch>
Maybe I'm totally wrong in this but don't we need an embracing `<Router>` tag around the `<Switch>`?
[React Router, quickstart](https://reactrouter.com/web/guides/quick-start)

2020-09-04 09:51 UTC, manuelpapa commented on src/components/CategoryButtons/CategoryButtons.js
> +  width: 128px;
In this case you also can think of a relative value `rem` to have a more consistent layout on different screen sizes.

2020-09-04 09:51 UTC, manuelpapa commented on src/components/CategoryButtons/CategoryButtons.js
> +  border-color: ${({ category }) =>
Now this is very clever and I think of stealing this idea 😄

2020-09-04 10:35 UTC, merged